// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2O2bPQR87qqbBg9KzvwFRn-n8VnMxjw',
    appId: '1:876051387322:web:1309af5e343d66285b8383',
    messagingSenderId: '876051387322',
    projectId: 'genuipoc',
    authDomain: 'genuipoc.firebaseapp.com',
    storageBucket: 'genuipoc.firebasestorage.app',
    measurementId: 'G-LXG6VTRBSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDApWylW2DxZMthk4unsX8NOk3TngfMdr0',
    appId: '1:876051387322:android:9fed49705c29dcc65b8383',
    messagingSenderId: '876051387322',
    projectId: 'genuipoc',
    storageBucket: 'genuipoc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz0PR0A1TCTLo__NSnPfbiZkquFwxrFI0',
    appId: '1:876051387322:ios:9abf5615284b7d9b5b8383',
    messagingSenderId: '876051387322',
    projectId: 'genuipoc',
    storageBucket: 'genuipoc.firebasestorage.app',
    iosBundleId: 'com.example.genUiPoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz0PR0A1TCTLo__NSnPfbiZkquFwxrFI0',
    appId: '1:876051387322:ios:9abf5615284b7d9b5b8383',
    messagingSenderId: '876051387322',
    projectId: 'genuipoc',
    storageBucket: 'genuipoc.firebasestorage.app',
    iosBundleId: 'com.example.genUiPoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo2O2bPQR87qqbBg9KzvwFRn-n8VnMxjw',
    appId: '1:876051387322:web:ae00c2d18441f1b25b8383',
    messagingSenderId: '876051387322',
    projectId: 'genuipoc',
    authDomain: 'genuipoc.firebaseapp.com',
    storageBucket: 'genuipoc.firebasestorage.app',
    measurementId: 'G-HPNVMDHEKR',
  );
}
